# Stage 1: Build
FROM node:22-alpine AS builder
 
WORKDIR /app
 
COPY ./apps/server/package.json ./apps/server/yarn.lock ./
 
RUN yarn install --frozen-lockfile
 
COPY ./apps/server ./
 
RUN yarn build:worker
 
# Stage 2: Production
FROM node:22-alpine
 
WORKDIR /app
 
COPY ./apps/server/package.json ./apps/server/yarn.lock ./
 
RUN yarn install --frozen-lockfile
 
COPY --from=builder /app/dist ./dist
 
ENV NODE_ENV=production
 
CMD ["node", "dist/worker.js"]
 